### ISSUE TITLE
Need Documentations for how to use

### ISSUE THREAD

**Issue by mdxabu** [zvyap/Hoyoverse-API#2]
The project is amazing, but no documentation for this project and how to use this.
@zvyap

**Comment by zvyap** [comment]
My bad. There is a basic document in https://github.com/zvyap/Hoyoverse-API/wiki/How-to-use-the-API
For feature such as daily check in, I will add the docs ASAP

If the request is not working well, please open a issues, I will fix it soon

Edit: https://github.com/zvyap/Hoyoverse-API/tree/master/src/test/java/com/zvyap/hoyoapi/test will help

**Comment by zvyap** [comment]
https://github.com/zvyap/Hoyoverse-API/wiki/Get-hoyoverse-API-token-(Hoyolab-Miyoushe)
&
https://github.com/zvyap/Hoyoverse-API/wiki/How-to-use-the-API

just updated with [v0.4](https://github.com/zvyap/Hoyoverse-API/releases/tag/v0.4)
